- name: apache2
  hosts: kumar1
  sudo: True
  tasks:
      - name: install apache2
        apt: name=apache2 update_cache=yes

      - name: started apache2
        service: name=apache2 state=started

