- name: mongodb
  hosts: kumar1
  sudo: True
  tasks:
       - name: mongodb key
         apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
       
       - name: Add MongoDB repository
         apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

       - name: install mongodb
         apt: pkg=mongodb-org state=latest update_cache=yes    
      
       - name: start mongodb
         service: name=mongod state=started
